### ISSUE TITLE
Wrong Image - contour allocation in 0.6.8

### ISSUE THREAD

**Issue by chrherold** [ZELLMECHANIK-DRESDEN/ShapeOut#121]
Images and contours are no match when clicking on an event. Likely a shift by 1.

**Comment by paulmueller** [comment]
This is probably due to the faster implementation that does not do much indexing. Sometimes the first frame of the contour is not missing although the first frame of the video is missing.

Possible fix suggested by @phidahl is to compare the contour timing "Contour in frame XXX" in contours.txt with the "time" column in the tdms file. This can be done for the first frame only which should not cause speed issues.

**Comment by paulmueller** [comment]
This should work again as expected now.
