### ISSUE TITLE
Display of Fluorescence Traces broken

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#159]
ShapeOut 0.7.6 shows only the first 9 points of fluorescence traces, if an event is clicked. This bug occurs on Windows and Mac OS.

**Comment by paulmueller** [comment]
I believe this is a regression introduced by https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/commit/657dd14edfe79eadf3013942d609f0d3304303d2#diff-09d96bca60b1eb83332b6fe0c8a4f322R232. If so, this bug was already present in 0.7.5.

Please try the latest build: https://ci.appveyor.com/project/paulmueller/ShapeOut
