### ISSUE TITLE
Cannot open sessions from Febr. 2017

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#174]
I get this error message:

[Window Title]
Error

[Content]
Traceback (most recent call last):
  File "gui\frontend.py", line 521, in OnMenuLoad
  File "gui\session.py", line 112, in open_session
  File "session\conversion.py", line 438, in update_session_hashes
NotImplementedError: Opening old sessions with deep hierarchy not possible!

[OK]

Going to much older versions is not an option. I need the LMM analysis
[20170203_p1234_mc_vergleich_FINAL_RETchilds.zip](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/files/1236118/20170203_p1234_mc_vergleich_FINAL_RETchilds.zip)

Data is on guck/members/philippr/RT-FDC/Experiments/2_reticulocytes/

.

**Comment by paulmueller** [comment]
The bug is that the "deep hierarchy" hint is wrong. The session file looks like you only created one hierarchy child per measurement (and not a hierarchy child of a hierarchy child). The conversion methods should have been able to deal with this scenario. I will have a look at the data. Either I can fix this in ShapeOut or I will give you a workaround by editing the session file.

**Comment by phidahl** [comment]
I could solve it.
I copy pasted the filters to a separate file, had to change the names of the columns and then imported the filters into a fresh session.

It would be important that old style column names are still recognized. otherwise old data will be not accessible anymore.

best

**Comment by paulmueller** [comment]
The problem was that the directory where the files were stored changed. If you opened the session on Windows and the data were stored in the same place (`R:\experiments_16_17\20161199_Philipp_RBC_Reticulocytes_Study\1 h time series P1toP4\`) then it would have worked. I am submitting a patch to fix this particular case (see commit below).
