### ISSUE TITLE
Smart determination of colors from previous analysis

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/ShapeOut#182]
If a user loads several measurements from a dataset using flow rate A, then selects separate colors for each measurement, ShapeOut should remember these colors if the user selects the datasets with flow rate B.

**Comment by paulmueller** [comment]
@chrherold  @derdeef
I need an example for this issue. Currently, the same colors are assigned if the number of measurements of the new analysis is <= than that of the old analysis. Therefore, as long as the number of measurements is the same, the colors are correctly reassigned. Is this not the case or is there another use case I did not think of?

**Comment by DerDeef** [comment]
Hi Paul,I think what was ment is the following: I load a set of data with different measurements. See picture... M1, M2, M3. I assign M1 with the colour red.
![1](https://user-images.githubusercontent.com/16649633/37773194-41c3d526-2ddd-11e8-83aa-db052facf61d.png)
When done I analyze M2..additionally.. meaning you have a larger number of m than the old analysis and the colours are reset. 
![grafik](https://user-images.githubusercontent.com/16649633/37773374-bad12a5e-2ddd-11e8-85e9-b445c966b37a.png)
But since we are working on the layout of a completely new ShapeOut (with Qt), you might wait?!
Best 
d

**Comment by paulmueller** [comment]
@chrherold Please create a new feature request in Shape-Out 2, e.g. "replace all dataslots in a session", if you think such a feature should be implemented. As you foresaw, this is not going to happen for Shape-Out 1.
