### ISSUE TITLE
ValueError: need more than 1 value to unpack in settings.py

### ISSUE THREAD

**Issue by maikherbig** [ZELLMECHANIK-DRESDEN/ShapeOut#232]
### General information
- Operating System: Windows 10 using Virtual machine for MacOs
- ShapeOut version: ShapeOut 0.8.8
- ShapeOut install: Windows 64bit installer (issue also present for 32bit installer)

### Steps to reproduce the problem
1. Open Shapeout

### Expected behavior
ShapeOut starts

### Actual behavior
There is an error message

```
Traceback (most recent call last):
  File "shapeout\ShapeOut.py" line 66, in <module>
  File "shapeout\ShapeOut.py" line 32, in main
  File "shapeout\__main__.py" lin 25, in prepare_app
  File "shapeout\gui\frontend.py" line 64, in __init__
  File "shapeout\gui\frontend.py" line 221, in InitUI
  File "shapeout\settings.py" line 60, in get_bool
  File "shapeout\settings.py" line 53, in load
ValueError: need more than 1 value to unpack
```

After reinstalling windows, the problem is gone but returns after a few weeks.

**Comment by paulmueller** [comment]
This should be fixed by the commit above. Once the build finishes, you can download the development version from here: https://ci.appveyor.com/project/paulmueller/ShapeOut/build/job/3a9a0sbix52h9jqe/artifacts

If anyone else is experiencing this issue and does not wish to use the development version: Delete the settings file
```
C:\\Users\\YOUR_USERNAME\\AppData\\Local\\shapeout.cfg
```
and ShapeOut should start again.

**Comment by maikherbig** [comment]
Deleting the settings file solves the issue! Thanks :)
