### ISSUE TITLE
Inversion of multiple polygon gates

### ISSUE THREAD

**Issue by KarenTessmer** [ZELLMECHANIK-DRESDEN/ShapeOut#253]
### General information
- Operating System: Windows 10
- ShapeOut version: ShapeOut 0.9.6.
- ShapeOut install: Windows 64bit installer

### Steps to reproduce the problem
1. load & analyze several samples
2. construct polygon gates for each sample (e.g. gate 0 for spl 1, gate 1 for spl 2 etc.) to gate for population of interest (e.g. fluorescence positives) in each sample separately
3. invert all polygon gates one by one (e.g. to select fluorescence negatives in each spl) 

### Data files
only tried .rtdc

### Expected behavior
all gates can be inverted

### Actual behavior
The first gate can be inverted, when I try with the second gate, ShapeOut does not reload the page correctly. The "filter" Tab does not reload correctly and the software crashes. 

```
PASTE ERROR MESSAGE HERE
```

**Comment by paulmueller** [comment]
Thanks for submitting this bug (I wasn't aware of it, because it is Windows-related). I think I resolved it in the development version. Please give it a try:

https://ci.appveyor.com/api/buildjobs/b6nm7r5b4029lg62/artifacts/.appveyor%2FOutput%2FShape-Out_0.9.6.post9_win_64bit_setup.exe

A workaround for version 0.9.6 and earlier could be to hit "SHIFT+ENTER". This should trigger a redraw of the panel.

**Comment by paulmueller** [comment]
Please reopen if this is not resolved in 0.9.7.
