### ISSUE TITLE
log plotting of fluorescence data

### ISSUE THREAD

**Issue by chrherold** [ZELLMECHANIK-DRESDEN/ShapeOut#264]
Windows 10
ShapeOut 1.0.0
observed in Guck Lab

Trying to plot fluorescence data FL1- Fl2 in log-log scale gives an error message

![image003](https://user-images.githubusercontent.com/13899168/73068858-8b43e100-3eac-11ea-8444-40ab1b018f2a.jpg)

and also 

<img width="425" alt="image" src="https://user-images.githubusercontent.com/13899168/73069157-479da700-3ead-11ea-8208-113a177d8cda.png">

Remark: no issue when plotting with Shape-Out2 where data look like this:
<img width="506" alt="image" src="https://user-images.githubusercontent.com/13899168/73069117-32287d00-3ead-11ea-81f7-d270eb33a693.png">

**Comment by paulmueller** [comment]
I can reproduce the MemoryError. I think it was due to the KDE accuracies which were computed in the log scale, but apparently this is not neccessary (anymore?). Please try this build: https://ci.appveyor.com/project/paulmueller/shapeout/builds/30406176/artifacts

I could not reproduce the first error you got. Could you maybe upload this dataset somewhere (after trying the latest build)?

Thanks!

**Comment by chrherold** [comment]
Latest build works like a charm. 
I could not reproduce the first error either and got the second as well. The first error happened for Martin and was also unusual to him. Originally, he wanted to show me the memory error but got this one when I stood next to him :). I think it's fine to ignore it until it would come up again.

**Comment by paulmueller** [comment]
I just figured this bug out and updated the fix. The changes are marginal, so I will proceed with the release right away.
